<div class="page-heading"><div><h1>Peminjaman Buku</h1><p>Lakukan transaksi peminjaman sesuai business logic dan validasi sistem.</p></div><div class="page-heading-actions"><a href="#form-peminjaman" class="btn btn-primary"><i class="bi bi-plus-lg me-1"></i> Pinjam Buku</a></div></div>
<div class="card mb-4" id="form-peminjaman">
  <div class="card-header bg-white"><strong>Form Peminjaman</strong><div class="text-muted" style="font-size:11px">Buku hanya dapat dipinjam jika stok tersedia dan mahasiswa belum mencapai 3 pinjaman aktif.</div></div>
  <div class="card-body">
    <form action="<?= BASE_URL ?>/peminjaman/store" method="POST" novalidate><div class="row g-3">
      <div class="col-md-3"><label class="form-label">NIM Anggota <span class="text-danger">*</span></label><input type="text" name="nim" list="daftar-nim" class="form-control <?= $this->errors('nim')?'is-invalid':'' ?>" value="<?= htmlspecialchars($this->old('nim')) ?>" placeholder="Contoh: 20241001"><datalist id="daftar-nim"><?php foreach($daftarAnggota as $a): ?><option value="<?= htmlspecialchars($a['nim']) ?>"><?= htmlspecialchars($a['nama']) ?></option><?php endforeach; ?></datalist><?php if($this->errors('nim')):?><div class="invalid-feedback"><?= htmlspecialchars($this->errors('nim')) ?></div><?php endif;?></div>
      <div class="col-md-4"><label class="form-label">Pilih Buku <span class="text-danger">*</span></label><select name="id_buku" class="form-select <?= $this->errors('id_buku')?'is-invalid':'' ?>"><option value="">-- Pilih Buku --</option><?php foreach($daftarBuku as $b): ?><option value="<?= (int)$b['id'] ?>" <?= (string)$this->old('id_buku')===(string)$b['id']?'selected':'' ?> <?= (int)$b['stok']<=0?'disabled':'' ?>><?= htmlspecialchars($b['kode_buku'].' - '.$b['judul']) ?> (Stok: <?= (int)$b['stok'] ?>)</option><?php endforeach;?></select><?php if($this->errors('id_buku')):?><div class="invalid-feedback"><?= htmlspecialchars($this->errors('id_buku')) ?></div><?php endif;?></div>
      <div class="col-md-2"><label class="form-label">Tanggal Pinjam <span class="text-danger">*</span></label><input type="date" name="tanggal_pinjam" class="form-control <?= $this->errors('tanggal_pinjam')?'is-invalid':'' ?>" value="<?= htmlspecialchars($this->old('tanggal_pinjam',date('Y-m-d'))) ?>"><?php if($this->errors('tanggal_pinjam')):?><div class="invalid-feedback"><?= htmlspecialchars($this->errors('tanggal_pinjam')) ?></div><?php endif;?></div>
      <div class="col-md-2"><label class="form-label">Tanggal Kembali <span class="text-danger">*</span></label><input type="date" name="tanggal_kembali" class="form-control <?= $this->errors('tanggal_kembali')?'is-invalid':'' ?>" value="<?= htmlspecialchars($this->old('tanggal_kembali',date('Y-m-d',strtotime('+7 days')))) ?>"><?php if($this->errors('tanggal_kembali')):?><div class="invalid-feedback"><?= htmlspecialchars($this->errors('tanggal_kembali')) ?></div><?php endif;?></div>
      <div class="col-12"><div class="form-actions"><button class="btn btn-primary" type="submit"><i class="bi bi-save me-1"></i> Simpan Peminjaman</button></div></div>
      
    </div></form>
  </div>
</div>
<div class="card"><div class="table-toolbar"><div><strong>Daftar Peminjaman</strong><div class="text-muted" style="font-size:10px">Riwayat transaksi peminjaman dan pengembalian.</div></div><div class="input-group input-group-sm table-search"><span class="input-group-text bg-white"><i class="bi bi-search"></i></span><input type="search" class="form-control" placeholder="Cari transaksi..." oninput="filterTable(this,'loanTable')"></div></div>
<div class="table-responsive"><table id="loanTable" class="table mb-0 align-middle"><thead><tr><th>No</th><th>ID Peminjaman</th><th>NIM</th><th>Nama Anggota</th><th>Judul Buku</th><th>Tgl Pinjam</th><th>Tgl Kembali</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php if(empty($daftarPeminjaman)): ?><tr><td colspan="9" class="text-center empty-state">Belum ada data peminjaman.</td></tr><?php else:$no=1;foreach($daftarPeminjaman as $p): ?><tr data-searchable><td><?= $no++ ?></td><td><strong><?= htmlspecialchars($p['kode_peminjaman']) ?></strong></td><td><?= htmlspecialchars($p['nim']) ?></td><td><?= htmlspecialchars($p['nama_anggota']) ?></td><td><?= htmlspecialchars($p['judul_buku']) ?></td><td><?= htmlspecialchars($p['tanggal_pinjam']) ?></td><td><?= htmlspecialchars($p['tanggal_kembali']) ?></td><td><?php if($p['status']==='dipinjam'): ?><span class="badge badge-status bg-warning-subtle text-warning-emphasis">Dipinjam</span><?php else: ?><span class="badge badge-status bg-success-subtle text-success">Kembali</span><?php endif;?></td><td><?php if($p['status']==='dipinjam'): ?><form action="<?= BASE_URL ?>/peminjaman/kembalikan" method="POST" class="d-inline" onsubmit="return confirm('Tandai buku ini sudah dikembalikan?');"><input type="hidden" name="id" value="<?= (int)$p['id'] ?>"><button class="btn btn-sm btn-success"><i class="bi bi-arrow-return-left me-1"></i>Kembalikan</button></form><?php else:?><span class="text-muted">-</span><?php endif;?></td></tr><?php endforeach;endif;?></tbody></table></div><div class="table-footer"><span>Menampilkan <?= count($daftarPeminjaman) ?> transaksi</span><a href="<?= BASE_URL ?>/pengembalian" class="text-decoration-none">Kelola pengembalian aktif →</a></div></div>
<script>function filterTable(input,id){const q=input.value.toLowerCase().trim();document.querySelectorAll('#'+id+' tbody tr[data-searchable]').forEach(r=>r.style.display=r.innerText.toLowerCase().includes(q)?'':'none');}</script>
